// Auto-generated by eslint/gen-todo.js on Sun, 02 Aug 2020 05:19:23 GMT
/* eslint-disable max-len, quote-props */

/**
  This file holds ESLint rules to ignore for specific files in the code base.
  There really should be none, but if there are, it means we're working on fixing
  them (likely because we introduced new rules), and you're welcome to help out.

  ## How to work on these todos:

  1. Pick a file to work on. You can see linter errors or warnings for a specific
     file by doing:

     $ ESLINT_NO_TODO=1 bin/lint.sh path/to/file.js

  2. Fix linter issues. This can be done by either editing the file or
     adjusting the relevant rule by editing ./base.config.js.

     If the file is from an external source and we don't expect to make changes
     other than replacing it entirely with a newer version, add it to the
     `ignorePatterns` of ./base.config.js.

     If a file really should be exempt from a certain rule, you can disable the
     rule for that file by adding a comment like "eslint-disable [rule-id-here]",
     just like the one at the top of this file. Read more about configuring ESLint
     with comments here:
     https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

  3. Run `node eslint/gen-todo.js` and confirm the file or the specific rule
     for the file you were working on has been removed from `overrides` below.
     Ideally, there should be no new additions to the `overrides` array.

  4. Confirm the linter is happy by running `bin/lint.sh`. There will be no
     output from the command if there are no issues.

  5. Make a PR.

  ## List of all ESLint rules that are disabled below

  Note: counts are from the time this file was generated and may not be accurate.

   * indent: 4018 - https://eslint.org/docs/rules/indent
   * func-args-comma-spacing: 2140 - ./plugin/docs/rules/func-args-comma-spacing.md
   * quotes: 620 - https://eslint.org/docs/rules/quotes
   * space-infix-ops: 464 - https://eslint.org/docs/rules/space-infix-ops
   * no-unused-vars: 387 - https://eslint.org/docs/rules/no-unused-vars
   * brace-style: 191 - https://eslint.org/docs/rules/brace-style
   * semi: 145 - https://eslint.org/docs/rules/semi
   * no-useless-escape: 144 - https://eslint.org/docs/rules/no-useless-escape
   * capitalized-comments: 109 - https://eslint.org/docs/rules/capitalized-comments
   * eqeqeq: 93 - https://eslint.org/docs/rules/eqeqeq
   * keyword-spacing: 90 - https://eslint.org/docs/rules/keyword-spacing
   * no-mixed-spaces-and-tabs: 48 - https://eslint.org/docs/rules/no-mixed-spaces-and-tabs
   * no-undef: 47 - https://eslint.org/docs/rules/no-undef
   * no-multiple-empty-lines: 43 - https://eslint.org/docs/rules/no-multiple-empty-lines
   * curly: 34 - https://eslint.org/docs/rules/curly
   * no-redeclare: 27 - https://eslint.org/docs/rules/no-redeclare
   * no-empty: 12 - https://eslint.org/docs/rules/no-empty
   * no-extra-semi: 10 - https://eslint.org/docs/rules/no-extra-semi
   * no-control-regex: 8 - https://eslint.org/docs/rules/no-control-regex
   * no-constant-condition: 5 - https://eslint.org/docs/rules/no-constant-condition
   * no-extra-boolean-cast: 5 - https://eslint.org/docs/rules/no-extra-boolean-cast
   * no-unreachable: 4 - https://eslint.org/docs/rules/no-unreachable
   * no-fallthrough: 1 - https://eslint.org/docs/rules/no-fallthrough
   * no-self-assign: 1 - https://eslint.org/docs/rules/no-self-assign

 */
module.exports = process.env.ESLINT_NO_TODO === "1" ? {} : {
    "overrides": [
        {
            "files": ["bin/optimise-svgs.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["boot/boot.js"],
            "rules": {
                "indent": "off", // Count: 2124
                "space-infix-ops": "off", // Count: 62
                "func-args-comma-spacing": "off", // Count: 15
                "semi": "off", // Count: 14
                "capitalized-comments": "off", // Count: 12
                "no-unused-vars": "off", // Count: 10
                "eqeqeq": "off", // Count: 8
                "keyword-spacing": "off", // Count: 8
                "no-redeclare": "off", // Count: 4
                "no-useless-escape": "off", // Count: 4
                "quotes": "off", // Count: 2
                "brace-style": "off", // Count: 1
                "no-control-regex": "off", // Count: 1
                "no-empty": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
                "no-mixed-spaces-and-tabs": "off", // Count: 1
            }
        },
        {
            "files": ["boot/bootprefix.js"],
            "rules": {
                "indent": "off", // Count: 59
                "capitalized-comments": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/commander.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/build.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/commands/deletetiddlers.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/fetch.js"],
            "rules": {
                "no-mixed-spaces-and-tabs": "off", // Count: 22
                "semi": "off", // Count: 5
                "no-unreachable": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/commands/import.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/init.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/listen.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/load.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/commands/makelibrary.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/output.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/render.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/rendertiddlers.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/savetiddlers.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/server.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/commands/setfield.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/deserializers.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "no-redeclare": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/editor/engines/framed.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/editor/engines/simple.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/editor/factory.js"],
            "rules": {
                "indent": "off", // Count: 6
                "func-args-comma-spacing": "off", // Count: 2
                "no-mixed-spaces-and-tabs": "off", // Count: 2
                "space-infix-ops": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/editor/operations/bitmap/rotate-left.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/editor/operations/text/excise.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/addprefix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/addsuffix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/after.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/all.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/before.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/commands.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/compare.js"],
            "rules": {
                "brace-style": "off", // Count: 12
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/contains.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/count.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/filters/days.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 9
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/each.js"],
            "rules": {
                "indent": "off", // Count: 2
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/eachday.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/editiondescription.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/editions.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/else.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/encodings.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 20
                "no-empty": "off", // Count: 2
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/enlist.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/field.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/fields.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 3
                "no-unused-vars": "off", // Count: 2
                "brace-style": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/get.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/getindex.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/has.js"],
            "rules": {
                "brace-style": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/is/blank.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/limit.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/listops.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 8
            }
        },
        {
            "files": ["core/modules/filters/match.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/math.js"],
            "rules": {
                "brace-style": "off", // Count: 44
                "semi": "off", // Count: 12
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/minlength.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/modules.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/moduletypes.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/next.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/prefix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/previous.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/range.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 13
                "keyword-spacing": "off", // Count: 4
                "brace-style": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/regexp.js"],
            "rules": {
                "no-extra-boolean-cast": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/removeprefix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/removesuffix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/sameday.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/sort.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/filters/sortsub.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/filters/splitbefore.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/storyviews.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/strings.js"],
            "rules": {
                "brace-style": "off", // Count: 14
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/suffix.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/tags.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
                "space-infix-ops": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/then.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/filters/title.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/untagged.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/wikiparserrules.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters/x-listops.js"],
            "rules": {
                "indent": "off", // Count: 137
                "func-args-comma-spacing": "off", // Count: 39
                "keyword-spacing": "off", // Count: 5
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/filters.js"],
            "rules": {
                "indent": "off", // Count: 12
                "no-useless-escape": "off", // Count: 6
                "brace-style": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
                "capitalized-comments": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/indexers/backlinks-index.js"],
            "rules": {
                "semi": "off", // Count: 5
                "func-args-comma-spacing": "off", // Count: 3
                "no-undef": "off", // Count: 3
                "no-mixed-spaces-and-tabs": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/indexers/field-indexer.js"],
            "rules": {
                "no-undef": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/indexers/tag-indexer.js"],
            "rules": {
                "no-undef": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/info/platform.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 8
                "brace-style": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/keyboard.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 9
                "indent": "off", // Count: 7
                "no-mixed-spaces-and-tabs": "off", // Count: 4
                "semi": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/macros/csvtiddlers.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 6
                "indent": "off", // Count: 3
                "no-unused-vars": "off", // Count: 3
                "semi": "off", // Count: 2
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/macros/displayshortcuts.js"],
            "rules": {
                "no-mixed-spaces-and-tabs": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/macros/resolvepath.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/macros/uniquetitle.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/parsers/audioparser.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/binaryparser.js"],
            "rules": {
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/csvparser.js"],
            "rules": {
                "indent": "off", // Count: 7
                "space-infix-ops": "off", // Count: 4
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/imageparser.js"],
            "rules": {
                "indent": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/parsers/parseutils.js"],
            "rules": {
                "indent": "off", // Count: 11
                "no-useless-escape": "off", // Count: 3
                "no-constant-condition": "off", // Count: 2
                "semi": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/pdfparser.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/textparser.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/videoparser.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/codeblock.js"],
            "rules": {
                "indent": "off", // Count: 5
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/codeinline.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/entity.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/extlink.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/filteredtranscludeblock.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 8
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/filteredtranscludeinline.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 8
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/html.js"],
            "rules": {
                "indent": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/import.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/list.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 7
                "no-useless-escape": "off", // Count: 2
                "no-constant-condition": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/macrocallinline.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/prettyextlink.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/quoteblock.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/styleblock.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/styleinline.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/syslink.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/table.js"],
            "rules": {
                "indent": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
                "capitalized-comments": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/transcludeblock.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 6
                "indent": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/transcludeinline.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 6
                "indent": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/typedblock.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/rules/wikilink.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/parsers/wikiparser/wikiparser.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 5
                "no-unused-vars": "off", // Count: 2
                "no-constant-condition": "off", // Count: 1
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/pluginswitcher.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/saver-handler.js"],
            "rules": {
                "indent": "off", // Count: 4
                "space-infix-ops": "off", // Count: 3
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/andtidwiki.js"],
            "rules": {
                "keyword-spacing": "off", // Count: 5
                "no-unused-vars": "off", // Count: 2
                "no-mixed-spaces-and-tabs": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/beaker.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
                "no-undef": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/download.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 5
                "no-unused-vars": "off", // Count: 2
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/fsosaver.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 3
                "brace-style": "off", // Count: 2
                "no-undef": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/gitea.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "no-unused-vars": "off", // Count: 3
                "keyword-spacing": "off", // Count: 2
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/github.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/savers/gitlab.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 3
                "quotes": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/savers/manualdownload.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/savers/msdownload.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/put.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 4
                "eqeqeq": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
                "quotes": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/tiddlyfox.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
                "no-useless-escape": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/tiddlyie.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 4
                "capitalized-comments": "off", // Count: 3
                "no-unused-vars": "off", // Count: 2
                "curly": "off", // Count: 1
                "eqeqeq": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/twedit.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 7
                "no-unused-vars": "off", // Count: 2
                "no-undef": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/savers/upload.js"],
            "rules": {
                "eqeqeq": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/server/authenticators/basic.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
                "quotes": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/server/authenticators/header.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/delete-tiddler.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/server/routes/get-favicon.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/get-file.js"],
            "rules": {
                "no-redeclare": "off", // Count: 1
                "no-self-assign": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/get-index.js"],
            "rules": {
                "indent": "off", // Count: 2
                "keyword-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/server/routes/get-login-basic.js"],
            "rules": {
                "quotes": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/server/routes/get-status.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/get-tiddler-html.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/get-tiddler.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/get-tiddlers-json.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/routes/put-tiddler.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
                "indent": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/server/server.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "semi": "off", // Count: 3
                "capitalized-comments": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/browser-messaging.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
                "no-mixed-spaces-and-tabs": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/commands.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/css-escape-polyfill.js"],
            "rules": {
                "eqeqeq": "off", // Count: 12
                "keyword-spacing": "off", // Count: 8
                "quotes": "off", // Count: 8
                "capitalized-comments": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/password.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/startup/plugins.js"],
            "rules": {
                "no-redeclare": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/render.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 3
                "no-mixed-spaces-and-tabs": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/rootwidget.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/startup.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/startup/story.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 6
                "capitalized-comments": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/startup/windows.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "brace-style": "off", // Count: 1
                "no-mixed-spaces-and-tabs": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/story.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 7
                "func-args-comma-spacing": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/storyviews/classic.js"],
            "rules": {
                "indent": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/storyviews/zoomin.js"],
            "rules": {
                "indent": "off", // Count: 5
                "space-infix-ops": "off", // Count: 5
                "eqeqeq": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/syncer.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 10
                "no-unused-vars": "off", // Count: 7
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/tiddler.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/upgraders/plugins.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/upgraders/system.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "no-redeclare": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/upgraders/themetweaks.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/crypto.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/csv.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/animator.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/browser.js"],
            "rules": {
                "indent": "off", // Count: 17
                "space-infix-ops": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/utils/dom/dom.js"],
            "rules": {
                "no-empty": "off", // Count: 3
                "no-unused-vars": "off", // Count: 2
                "space-infix-ops": "off", // Count: 2
                "indent": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/dragndrop.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 6
                "func-args-comma-spacing": "off", // Count: 2
                "no-mixed-spaces-and-tabs": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
                "semi": "off", // Count: 2
                "indent": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/http.js"],
            "rules": {
                "indent": "off", // Count: 2
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/utils/dom/keyboard.js"],
            "rules": {
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/modal.js"],
            "rules": {
                "indent": "off", // Count: 4
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/utils/dom/notifier.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/popup.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 4
                "space-infix-ops": "off", // Count: 4
                "no-mixed-spaces-and-tabs": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/dom/scroller.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 1
                "no-mixed-spaces-and-tabs": "off", // Count: 1
                "quotes": "off", // Count: 1
                "semi": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/edition-info.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 4
                "no-empty": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/fakedom.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 28
                "no-unused-vars": "off", // Count: 3
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/utils/filesystem.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 7
                "no-unused-vars": "off", // Count: 3
                "no-extra-boolean-cast": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
                "indent": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "no-control-regex": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/logger.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 2
                "indent": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/parsetree.js"],
            "rules": {
                "indent": "off", // Count: 5
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/utils/performance.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 3
                "semi": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/pluginmaker.js"],
            "rules": {
                "indent": "off", // Count: 4
                "space-infix-ops": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/transliterate.js"],
            "rules": {
                "semi": "off", // Count: 2
                "no-control-regex": "off", // Count: 1
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/utils/utils.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 24
                "quotes": "off", // Count: 21
                "capitalized-comments": "off", // Count: 18
                "no-useless-escape": "off", // Count: 18
                "space-infix-ops": "off", // Count: 18
                "brace-style": "off", // Count: 4
                "no-control-regex": "off", // Count: 4
                "semi": "off", // Count: 4
                "no-unused-vars": "off", // Count: 3
                "eqeqeq": "off", // Count: 2
                "indent": "off", // Count: 2
                "keyword-spacing": "off", // Count: 2
                "curly": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/action-createtiddler.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 5
                "keyword-spacing": "off", // Count: 3
                "no-redeclare": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/action-deletefield.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/widgets/action-deletetiddler.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "space-infix-ops": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/action-listops.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 15
                "no-unused-vars": "off", // Count: 4
                "indent": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/action-navigate.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/action-popup.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "no-useless-escape": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/widgets/action-sendmessage.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/widgets/action-setfield.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "eqeqeq": "off", // Count: 3
            }
        },
        {
            "files": ["core/modules/widgets/browse.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/button.js"],
            "rules": {
                "brace-style": "off", // Count: 4
                "indent": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/checkbox.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/codeblock.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/count.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/diff-text.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 1
                "no-control-regex": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/draggable.js"],
            "rules": {
                "brace-style": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/widgets/droppable.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 9
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/dropzone.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 12
                "no-unused-vars": "off", // Count: 3
                "no-redeclare": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/edit-binary.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/edit-bitmap.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 12
                "space-infix-ops": "off", // Count: 9
                "capitalized-comments": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/edit-shortcut.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
                "capitalized-comments": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/element.js"],
            "rules": {
                "indent": "off", // Count: 4
            }
        },
        {
            "files": ["core/modules/widgets/encrypt.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/entity.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/fieldmangler.js"],
            "rules": {
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/fields.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 5
                "keyword-spacing": "off", // Count: 3
                "curly": "off", // Count: 2
                "indent": "off", // Count: 2
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/importvariables.js"],
            "rules": {
                "keyword-spacing": "off", // Count: 3
                "eqeqeq": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/keyboard.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/link.js"],
            "rules": {
                "indent": "off", // Count: 6
                "brace-style": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 2
                "semi": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/linkcatcher.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["core/modules/widgets/list.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 11
                "indent": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/macrocall.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
                "indent": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/navigator.js"],
            "rules": {
                "indent": "off", // Count: 26
                "func-args-comma-spacing": "off", // Count: 2
                "no-empty": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/password.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/radio.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
                "no-mixed-spaces-and-tabs": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/range.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 7
                "quotes": "off", // Count: 3
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/raw.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/reveal.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 4
                "capitalized-comments": "off", // Count: 1
                "indent": "off", // Count: 1
                "no-mixed-spaces-and-tabs": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/scrollable.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
                "indent": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/select.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 3
                "keyword-spacing": "off", // Count: 3
                "semi": "off", // Count: 3
                "space-infix-ops": "off", // Count: 3
                "eqeqeq": "off", // Count: 1
                "indent": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/setvariable.js"],
            "rules": {
                "eqeqeq": "off", // Count: 2
                "no-mixed-spaces-and-tabs": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/text.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/transclude.js"],
            "rules": {
                "indent": "off", // Count: 7
            }
        },
        {
            "files": ["core/modules/widgets/view.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/widget.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 17
                "indent": "off", // Count: 3
                "no-unused-vars": "off", // Count: 3
                "eqeqeq": "off", // Count: 2
                "keyword-spacing": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
                "brace-style": "off", // Count: 1
                "curly": "off", // Count: 1
                "no-empty": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/widgets/wikify.js"],
            "rules": {
                "indent": "off", // Count: 5
            }
        },
        {
            "files": ["core/modules/wiki-bulkops.js"],
            "rules": {
                "indent": "off", // Count: 2
                "semi": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["core/modules/wiki.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 35
                "no-unused-vars": "off", // Count: 10
                "indent": "off", // Count: 9
                "func-args-comma-spacing": "off", // Count: 6
                "capitalized-comments": "off", // Count: 3
                "no-useless-escape": "off", // Count: 3
                "semi": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-backlinks.js"],
            "rules": {
                "quotes": "off", // Count: 74
                "func-args-comma-spacing": "off", // Count: 35
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-compare-filter.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 11
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-filters.js"],
            "rules": {
                "indent": "off", // Count: 564
                "func-args-comma-spacing": "off", // Count: 217
                "quotes": "off", // Count: 35
                "capitalized-comments": "off", // Count: 8
                "brace-style": "off", // Count: 6
                "no-useless-escape": "off", // Count: 5
                "no-multiple-empty-lines": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-html-parser.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 565
                "quotes": "off", // Count: 170
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-tags.js"],
            "rules": {
                "indent": "off", // Count: 120
                "func-args-comma-spacing": "off", // Count: 91
                "quotes": "off", // Count: 5
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-tiddler.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 7
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-utils.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 39
                "quotes": "off", // Count: 11
                "capitalized-comments": "off", // Count: 3
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-widget.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 212
                "indent": "off", // Count: 40
                "capitalized-comments": "off", // Count: 3
                "keyword-spacing": "off", // Count: 2
                "semi": "off", // Count: 2
                "no-extra-semi": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-wikitext-parser.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 515
                "quotes": "off", // Count: 175
            }
        },
        {
            "files": ["editions/test/tiddlers/tests/test-wikitext.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 21
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/absolute/b.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/absolute/program.js"],
            "rules": {
                "quotes": "off", // Count: 6
                "func-args-comma-spacing": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/absolute/submodule/a.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/allTests.js"],
            "rules": {
                "no-undef": "off", // Count: 11
                "quotes": "off", // Count: 11
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/cyclic/a.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/cyclic/b.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/cyclic/program.js"],
            "rules": {
                "quotes": "off", // Count: 9
                "func-args-comma-spacing": "off", // Count: 5
                "no-multiple-empty-lines": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/determinism/program.js"],
            "rules": {
                "quotes": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/determinism/submodule/a.js"],
            "rules": {
                "quotes": "off", // Count: 4
                "indent": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/exactExports/a.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 2
                "indent": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/exactExports/program.js"],
            "rules": {
                "quotes": "off", // Count: 5
                "func-args-comma-spacing": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/hasOwnProperty/program.js"],
            "rules": {
                "quotes": "off", // Count: 5
                "no-unused-vars": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/method/a.js"],
            "rules": {
                "indent": "off", // Count: 4
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/method/program.js"],
            "rules": {
                "quotes": "off", // Count: 7
                "func-args-comma-spacing": "off", // Count: 4
                "eqeqeq": "off", // Count: 3
                "brace-style": "off", // Count: 2
                "semi": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/missing/program.js"],
            "rules": {
                "quotes": "off", // Count: 8
                "func-args-comma-spacing": "off", // Count: 3
                "indent": "off", // Count: 3
                "keyword-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/monkeys/a.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/monkeys/program.js"],
            "rules": {
                "quotes": "off", // Count: 5
                "func-args-comma-spacing": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/nested/a/b/c/d.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/nested/program.js"],
            "rules": {
                "quotes": "off", // Count: 5
                "func-args-comma-spacing": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/relative/program.js"],
            "rules": {
                "quotes": "off", // Count: 6
                "func-args-comma-spacing": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/relative/submodule/a.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/test.js"],
            "rules": {
                "indent": "off", // Count: 8
                "semi": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/transitive/a.js"],
            "rules": {
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/transitive/b.js"],
            "rules": {
                "no-multiple-empty-lines": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/transitive/c.js"],
            "rules": {
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["editions/testcommonjs/tiddlers/transitive/program.js"],
            "rules": {
                "quotes": "off", // Count: 5
                "func-args-comma-spacing": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
            }
        },
        {
            "files": ["editions/tw5.com/tiddlers/system/if-macro.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/aws/modules/command.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 4
                "no-redeclare": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/aws/modules/init.js"],
            "rules": {
                "indent": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/aws/modules/utils.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/bibtex/deserializer.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/browser-sniff/browser.js"],
            "rules": {
                "brace-style": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/browser-storage/rawmarkup.js"],
            "rules": {
                "no-undef": "off", // Count: 16
                "space-infix-ops": "off", // Count: 2
                "no-empty": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/browser-storage/startup.js"],
            "rules": {
                "indent": "off", // Count: 3
                "no-unused-vars": "off", // Count: 3
                "space-infix-ops": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/cecily/cecily.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/classictools/modules/recipe.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 3
            }
        },
        {
            "files": ["plugins/tiddlywiki/codemirror/engine.js"],
            "rules": {
                "indent": "off", // Count: 22
                "keyword-spacing": "off", // Count: 5
                "space-infix-ops": "off", // Count: 4
                "no-unused-vars": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 2
                "semi": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/consent-banner/raw-widget.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/consent-banner/startup.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 5
                "no-unused-vars": "off", // Count: 3
            }
        },
        {
            "files": ["plugins/tiddlywiki/d3/barwidget.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 43
                "brace-style": "off", // Count: 42
                "capitalized-comments": "off", // Count: 5
                "indent": "off", // Count: 4
                "keyword-spacing": "off", // Count: 4
                "curly": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/d3/cloudwidget.js"],
            "rules": {
                "brace-style": "off", // Count: 12
                "func-args-comma-spacing": "off", // Count: 12
                "space-infix-ops": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/dynannotate/modules/dynannotate.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 7
                "semi": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/dynannotate/modules/selection-tracker.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 3
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/dynannotate/modules/textmap.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 5
                "semi": "off", // Count: 3
                "indent": "off", // Count: 2
                "space-infix-ops": "off", // Count: 2
                "no-empty": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/dynaview/dynaview.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
                "capitalized-comments": "off", // Count: 1
                "func-args-comma-spacing": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
                "no-undef": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/evernote/modules/enex-deserializer.js"],
            "rules": {
                "semi": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/external-attachments/startup.js"],
            "rules": {
                "indent": "off", // Count: 2
                "semi": "off", // Count: 2
                "capitalized-comments": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/filesystem/filesystemadaptor.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 5
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/freelinks/plain-text.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/freelinks/text.js"],
            "rules": {
                "indent": "off", // Count: 3
            }
        },
        {
            "files": ["plugins/tiddlywiki/googleanalytics/googleanalytics.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 11
                "quotes": "off", // Count: 7
                "brace-style": "off", // Count: 2
                "no-undef": "off", // Count: 2
                "semi": "off", // Count: 2
                "indent": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/innerwiki/data.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/innerwiki/screenshot.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/jasmine/jasmine-plugin.js"],
            "rules": {
                "capitalized-comments": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/jszip/startup.js"],
            "rules": {
                "indent": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/katex/latex-parser.js"],
            "rules": {
                "eqeqeq": "off", // Count: 1
                "quotes": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/katex/wrapper.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 7
                "indent": "off", // Count: 3
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/mobiledragdrop/startup.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/nodewebkitsaver/nodewebkit.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
                "eqeqeq": "off", // Count: 1
                "no-useless-escape": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/pluginlibrary/libraryserver.js"],
            "rules": {
                "eqeqeq": "off", // Count: 2
                "no-undef": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/qrcode/makeqr.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 4
                "keyword-spacing": "off", // Count: 2
                "quotes": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/railroad/components.js"],
            "rules": {
                "semi": "off", // Count: 17
                "space-infix-ops": "off", // Count: 5
                "no-mixed-spaces-and-tabs": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/railroad/parser.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 5
                "semi": "off", // Count: 3
                "indent": "off", // Count: 1
                "keyword-spacing": "off", // Count: 1
                "no-constant-condition": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/railroad/typed-parser.js"],
            "rules": {
                "indent": "off", // Count: 5
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/railroad/wrapper.js"],
            "rules": {
                "func-args-comma-spacing": "off", // Count: 5
                "space-infix-ops": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/savetrail/savetrail.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 2
                "no-useless-escape": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/share/rawmarkup.js"],
            "rules": {
                "no-undef": "off", // Count: 2
                "space-infix-ops": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/stacked-view/stacked.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 10
                "no-unused-vars": "off", // Count: 7
                "no-redeclare": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tahoelafs/saver.js"],
            "rules": {
                "eqeqeq": "off", // Count: 2
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/text-slicer/modules/commands/slice.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/text-slicer/modules/slicer.js"],
            "rules": {
                "indent": "off", // Count: 52
                "func-args-comma-spacing": "off", // Count: 7
                "no-unused-vars": "off", // Count: 3
                "semi": "off", // Count: 3
                "brace-style": "off", // Count: 2
                "capitalized-comments": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
                "no-multiple-empty-lines": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/text-slicer/modules/startup/slicer-startup.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tiddlyweb/tiddlywebadaptor.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 8
                "space-infix-ops": "off", // Count: 4
                "capitalized-comments": "off", // Count: 2
                "indent": "off", // Count: 2
                "keyword-spacing": "off", // Count: 2
                "func-args-comma-spacing": "off", // Count: 1
                "no-empty": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tw2parser/classictransclude.js"],
            "rules": {
                "no-useless-escape": "off", // Count: 9
                "curly": "off", // Count: 8
                "space-infix-ops": "off", // Count: 6
                "eqeqeq": "off", // Count: 4
                "brace-style": "off", // Count: 3
                "func-args-comma-spacing": "off", // Count: 2
                "keyword-spacing": "off", // Count: 2
                "no-extra-semi": "off", // Count: 1
                "no-unused-vars": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tw2parser/entry.js"],
            "rules": {
                "keyword-spacing": "off", // Count: 1
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tw2parser/parameteradapter.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 19
                "quotes": "off", // Count: 7
                "eqeqeq": "off", // Count: 4
                "curly": "off", // Count: 3
                "no-unused-vars": "off", // Count: 3
                "semi": "off", // Count: 2
                "indent": "off", // Count: 1
                "no-extra-semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tw2parser/wikitextparser.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 9
                "capitalized-comments": "off", // Count: 5
                "curly": "off", // Count: 5
                "no-multiple-empty-lines": "off", // Count: 2
                "keyword-spacing": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/tw2parser/wikitextrules.js"],
            "rules": {
                "indent": "off", // Count: 651
                "space-infix-ops": "off", // Count: 41
                "eqeqeq": "off", // Count: 33
                "no-useless-escape": "off", // Count: 25
                "brace-style": "off", // Count: 22
                "curly": "off", // Count: 11
                "capitalized-comments": "off", // Count: 7
                "keyword-spacing": "off", // Count: 7
                "no-unused-vars": "off", // Count: 5
                "no-extra-boolean-cast": "off", // Count: 2
                "no-multiple-empty-lines": "off", // Count: 2
                "semi": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/twitter/twitter-widget.js"],
            "rules": {
                "indent": "off", // Count: 3
                "no-unused-vars": "off", // Count: 2
                "no-undef": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/xlsx-utils/deserializer.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 2
            }
        },
        {
            "files": ["plugins/tiddlywiki/xlsx-utils/importer.js"],
            "rules": {
                "space-infix-ops": "off", // Count: 5
                "semi": "off", // Count: 4
                "func-args-comma-spacing": "off", // Count: 1
                "no-fallthrough": "off", // Count: 1
            }
        },
        {
            "files": ["plugins/tiddlywiki/xlsx-utils/xlsx-import-command.js"],
            "rules": {
                "no-unused-vars": "off", // Count: 1
            }
        },
    ],
    "ignorePatterns": [
        "plugins/tiddlywiki/innerwiki/innerwiki.js", // Fatal: Parsing error: Unexpected token browser
        "plugins/tiddlywiki/markdown/wrapper.js", // Fatal: Parsing error: The keyword 'let' is reserved
    ],
};
